# Generated by Django 4.1.3 on 2022-12-21 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transacted_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(max_length=10)),
                ('from_wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rupya.wallet')),
                ('to_wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rupya.wallet')),
            ],
        ),
    ]
