# Generated by Django 4.1.3 on 2022-12-21 13:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rupya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transacted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 21, 13, 35, 12, 841768, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='transfer',
            name='from_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rupya.wallet'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rupya.wallet'),
        ),
        migrations.AddField(
            model_name='entries',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='rupya.wallet'),
        ),
    ]
