# Generated by Django 4.1.3 on 2022-12-21 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rupya', '0003_transactions_delete_transfer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entries',
            new_name='Entrie',
        ),
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
