# Generated by Django 4.1.4 on 2022-12-29 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rupya', '0004_rename_entries_entrie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.BigIntegerField()),
                ('amount', models.IntegerField()),
                ('req_status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('P', 'Rejected')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rupya.wallet')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rupya.wallet')),
            ],
        ),
    ]
