TRANSACTION_TYPE_DEPOSIT = 'deposit'
TRANSACTION_TYPE_WITHDRAW = 'withdraw'
TRANSACTION_TYPE_SEND = 'send'
TRANSACTION_TYPE_RECEIVE = 'receive'
TRANSACTION_TYPE_REQUEST = 'request'

# Model, CashRequest
CASHREQUEST_STATUS_PENDING = 'P'
CASHREQUEST_STATUS_ACCEPTED = 'A'
CASHREQUEST_STATUS_REJECTED = 'P'

CASHREQUEST_STATUS_CHOICES = [
    (CASHREQUEST_STATUS_PENDING, 'Pending'),
    (CASHREQUEST_STATUS_ACCEPTED, 'Accepted'),
    (CASHREQUEST_STATUS_REJECTED, 'Rejected'),
]